# Fonts
# https://sw.kovidgoyal.net/kitty/conf/#fonts
font_family      family="CaskaydiaCove Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Text Cursor Customization
# https://sw.kovidgoyal.net/kitty/conf/#text-cursor-customization
cursor_shape          block
cursor_blink_interval 0
cursor_trail          200
cursor_trail_color    #ff0000

# Terminal bell
# https://sw.kovidgoyal.net/kitty/conf/#terminal-bell
enable_audio_bell     no

# Window Layout
# https://sw.kovidgoyal.net/kitty/conf/#window-layout
hide_window_decorations no

# Tab bar
# https://sw.kovidgoyal.net/kitty/conf/#tab-bar
# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Advanced
# https://sw.kovidgoyal.net/kitty/conf/#advanced
shell_integration     no-cursor

# Search kitten for kitty
# https://github.com/trygveaa/kitty-kitten-search#installation
map kitty_mod+/      launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
